name: PR quality

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  quality:
    uses: in2workspace/eudistack-devops-workflows/.github/workflows/spa-pr.yml@5f949958c1932739d0763fd7d733b6b1a634eba2
    with:
      lint_command: npm run lint
      build_command: >-
        npm run build -- --configuration development --output-path=./dist/out
      build_output: dist/out/browser
      serve_command: python3 -m http.server 8080 --directory dist/out/browser
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  license-compliance:
    uses: in2workspace/eudistack-devops-workflows/.github/workflows/common-license-gate.yml@5f949958c1932739d0763fd7d733b6b1a634eba2
    with:
      setup_java: false
      install_command: npm ci
      sbom_command: npm run sbom
      sbom_path: build/sbom/sbom.json

  analyze:
    uses: in2workspace/eudistack-devops-workflows/.github/workflows/common-codeql-javascript.yml@5f949958c1932739d0763fd7d733b6b1a634eba2