name: Release SPA

on:
  push:
    branches:
      - 'release/v*.*.*'

permissions:
  actions: read
  contents: write
  id-token: write
  attestations: write

jobs:
  release:
    uses: in2workspace/eudistack-devops-workflows/.github/workflows/spa-release.yml@c2061f16b4fcacb12d8a4439899ed73c6d3a17cd
    with:
      project_name: eudistack
      region_code: ew1
      spa_prefix: /verifier/
      staging_environment: stg
      production_environment: pro
      staging_smoke_url: https://sandbox.stg.eudistack.net/verifier/
      production_smoke_url: https://sandbox.eudistack.net/verifier/
      build_command: >-
        npm run build -- --configuration production --output-path=./dist/out
        --base-href=/verifier/ --deploy-url=/verifier/
      build_output: dist/out/browser
      lint_command: npm run lint
      runtime_required_variables: API_BASE_URL
    secrets: inherit